<?php

/**
 * @file
 * Contains smile_entity.module.
 */

use Drupal\Core\Render\Element;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function smile_entity_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the smile_entity module.
    case 'help.page.smile_entity':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Entity(Practice)') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function smile_entity_theme($existing, $type, $theme, $path) {
  $theme = [
    'smile_entity' => [
      'path' => $path . '/templates',
      'template' => 'smile-entity',
      'render element' => 'elements',
    ],
  ];
  return $theme;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function template_preprocess_smile_entity(&$variables) {
  $variables['value'] = [];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['value'][$key] = $variables['elements'][$key];
  }
}


